title: Oktiva Rahmawati Dhewi
description: A fresh graduate with experience in data cleaning, data manipulation, data visualization, data analysis, modeling, and interpreting data sets. Skilled in R, Looker Studio, Excel, Python, and SQL. 
theme: jekyll-theme-minimal
