title: Oktiva Rahmawati Dhewi
logo: /assets/img/rd-oktiva.webp
description: A fresh graduate with experience in data cleaning, data manipulation, data visualization, data analysis, and data interpretation

theme: jekyll-theme-minimal
